"""Add branch_name to user

Revision ID: 0d9a72b0217f
Revises: 83354e5027a6
Create Date: 2026-07-07 13:57:18.196946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d9a72b0217f'
down_revision: Union[str, Sequence[str], None] = '83354e5027a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('branch_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'branch_name')
    # ### end Alembic commands ###
