"""update datetime to timestamptz

Revision ID: 138106bedb00
Revises: 990efb6efc85
Create Date: 2026-07-09 14:21:54.489412

"""
from typing import Sequence, Union

from alembic import op
import app.models
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '138106bedb00'
down_revision: Union[str, Sequence[str], None] = '990efb6efc85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('app_settings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=app.models.UTCDateTime(timezone=True),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('content', 'scheduled_publish_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=app.models.UTCDateTime(timezone=True),
               postgresql_using="scheduled_publish_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('content', 'published_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=app.models.UTCDateTime(timezone=True),
               postgresql_using="published_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('content', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=app.models.UTCDateTime(timezone=True),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('content', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=app.models.UTCDateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('departments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=app.models.UTCDateTime(timezone=True),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('departments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=app.models.UTCDateTime(timezone=True),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('modules', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=app.models.UTCDateTime(timezone=True),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('modules', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=app.models.UTCDateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('sso_token_log', 'consumed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=app.models.UTCDateTime(timezone=True),
               postgresql_using="consumed_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('user_progress', 'completed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=app.models.UTCDateTime(timezone=True),
               postgresql_using="completed_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('user_progress', 'last_accessed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=app.models.UTCDateTime(timezone=True),
               postgresql_using="last_accessed_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=app.models.UTCDateTime(timezone=True),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=app.models.UTCDateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('user_progress', 'last_accessed_at',
               existing_type=app.models.UTCDateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="last_accessed_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('user_progress', 'completed_at',
               existing_type=app.models.UTCDateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="completed_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('sso_token_log', 'consumed_at',
               existing_type=app.models.UTCDateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="consumed_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('modules', 'updated_at',
               existing_type=app.models.UTCDateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('modules', 'created_at',
               existing_type=app.models.UTCDateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('departments', 'updated_at',
               existing_type=app.models.UTCDateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('departments', 'created_at',
               existing_type=app.models.UTCDateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('content', 'updated_at',
               existing_type=app.models.UTCDateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('content', 'created_at',
               existing_type=app.models.UTCDateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('content', 'published_at',
               existing_type=app.models.UTCDateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="published_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('content', 'scheduled_publish_at',
               existing_type=app.models.UTCDateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="scheduled_publish_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('app_settings', 'updated_at',
               existing_type=app.models.UTCDateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    # ### end Alembic commands ###
