"""Add additional_notes to Content

Revision ID: 83354e5027a6
Revises: 255fe7d9d802
Create Date: 2026-06-24 14:25:05.723671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83354e5027a6'
down_revision: Union[str, Sequence[str], None] = '255fe7d9d802'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content', sa.Column('additional_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content', 'additional_notes')
    # ### end Alembic commands ###
