"""remove_sheet_row_hash

Revision ID: 990efb6efc85
Revises: a26acd46b629
Create Date: 2026-07-09 12:20:14.603259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '990efb6efc85'
down_revision: Union[str, Sequence[str], None] = 'a26acd46b629'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content', 'sheet_row_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content', sa.Column('sheet_row_hash', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
